version: '3.3'

services:

  db:
    image: 'mysql:5.7'
    volumes:
      - './.data/mysql:/var/lib/mysql'
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password

  wordpress:
    depends_on:
      - db
    image: 'wordpress:5.7-apache'
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./.data/wordpress:/var/www/html"
      - "./.data/plugins:/var/www/html/wp-content/plugins"
      - "./twister:/var/www/html/wp-content/plugins/twister:ro"

  wpcli:
    depends_on:
      - wordpress
    image: 'wordpress:5.7-cli'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes_from:
      - wordpress
